//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioscoMF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        public int Id { get; set; }
        public string ProductoId { get; set; }
        public double Precio { get; set; }
        public double Ancho { get; set; }
        public double Largo { get; set; }
        public double Peso { get; set; }
        public int ProductoId1 { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
